#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
	if ! grep database_connection /etc/designate/designate.conf | grep -qv "database_connection = sqlite:////var/lib/designate/designate.sqlite"
	then
		# This needs to be AFTER the debhelper include above, so the config file is in place.
		su -s /bin/sh -c 'cd /tmp && designate-manage database-init' designate || true
		su -s /bin/sh -c 'cd /tmp && designate-manage database-sync' designate
	fi
fi