#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
	if ! grep database_connection /etc/moniker/moniker.conf | grep -qv "database_connection = sqlite:////var/lib/moniker/moniker.sqlite"
	then
		# This needs to be AFTER the debhelper include above, so the config file is in place.
		su -s /bin/sh -c 'cd /tmp && moniker-manage database-init' moniker || true
		su -s /bin/sh -c 'cd /tmp && moniker-manage database-sync' moniker
	fi
fi